### ISSUE TITLE
Bug: clone is not a function

### ISSUE THREAD

**Issue by mtx62** [algolia/algoliasearch-client-javascript#714] opened 2018-07-13 03:34 UTC
"algoliasearch": "^3.29.0",
"react-native": "^0.54.2",
"react": "^16.3.0-alpha.1",

**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**

TypeError: clone is not a function
    at AlgoliaSearchReactNative.AlgoliaSearchCore._setHostIndexByType (e6dc786a-6c3f-48f9-9…e50c15d46b1d:186970)
    at AlgoliaSearchReactNative.AlgoliaSearchCore._incrementHostIndex (e6dc786a-6c3f-48f9-9…e50c15d46b1d:186981)
    at retryRequestWithHigherTimeout (e6dc786a-6c3f-48f9-9…e50c15d46b1d:186633)
    at tryFallback (e6dc786a-6c3f-48f9-9…e50c15d46b1d:186616)
    at tryCallOne (e6dc786a-6c3f-48f9-9…-e50c15d46b1d:14083)
    at e6dc786a-6c3f-48f9-9…-e50c15d46b1d:14184
    at e6dc786a-6c3f-48f9-9…-e50c15d46b1d:15504
    at _callTimer (e6dc786a-6c3f-48f9-9…-e50c15d46b1d:15393)
    at _callImmediatesPass (e6dc786a-6c3f-48f9-9…-e50c15d46b1d:15429)
    at Object.callImmediates (e6dc786a-6c3f-48f9-9…-e50c15d46b1d:15648)

**If the current behavior is a bug, please provide all the steps to reproduce and a minimal
[JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install`
and `npm start`.**
It's React Native app loading list of Ads
**What is the expected behavior?**
Load ads without crash.

Best regards.

**Comment by Haroenv** [comment] 2018-07-13 07:58
@mtx62 could you please give the minimal code that generates this error? This stack trace won't help me find the error, since I'd need the usage first. If not possible to make it public, you can send an email with the minimal code that throws this error to support@algolia.com.

**Comment by mtx62** [comment] 2018-07-13 15:03
Hi @Haroenv,
As requested I send the code to support@algolia.com from my email.
Thank you.

**Comment by mtx62** [comment] 2018-07-13 15:05
by the way
I think it's related to https://github.com/algolia/algoliasearch-client-javascript/issues/681.

**Comment by Haroenv** [comment] 2018-07-13 15:18
@mtx62, which email did you use to send a message, I can't find it :)

**Comment by mtx62** [comment] 2018-07-13 15:20
@Haroenv  3zoznr@gmail.com

**Comment by twillstudio** [comment] 2018-09-26 23:37
Hi everyone, did anyone find the solution for this problem ? Thanks!

**Comment by Haroenv** [comment] 2018-09-27 06:59
I haven't been able to find a reproducing project, but all the versions in the OP have been updated since, can be checked if this is fixed by using the latest versions? 

To find a solution, a minimal project in which this happens has to be made 🙂 

Thanks!

**Comment by samouss** [comment] 2018-10-04 15:59
This issue arise with the version 0.54.x of React Native. You should either upgrade on 0.55.x or downgrade on the 0.53.x. I'm closing the issue, feel free to open a new one if the issue still persist.

**Closed by samouss** 2018-10-04 15:59 UTC
Labels: bug, more info needed, question, react native
