### ISSUE TITLE
[bug]: Compling errors with Angular

### ISSUE THREAD

**Issue by JGSolutions** [algolia/algoliasearch-client-javascript#1566] opened 2024-10-21 11:10 UTC
### Description

Starting with versionn 5.8.0 when builldinng the project tinn angular i get these errors:

### Client

Search

### Version

5.8.0

### Relevant log output

```shell
✘ [ERROR] No matching export in "node_modules/@algolia/client-abtesting/dist/builds/browser.js" for import "Status"

    node_modules/algoliasearch/dist/browser.js:56:9:
      56 │ import { Status } from "@algolia/client-abtesting";
         ╵          ~~~~~~


✘ [ERROR] No matching export in "node_modules/@algolia/client-personalization/dist/builds/browser.js" for import "EventType"

    node_modules/algoliasearch/dist/browser.js:57:9:
      57 │ import { EventType } from "@algolia/client-personalization";
         ╵          ~~~~~~~~~


✘ [ERROR] No matching export in "node_modules/@algolia/client-abtesting/dist/builds/node.js" for import "Status"

    node_modules/algoliasearch/dist/node.js:56:9:
      56 │ import { Status } from "@algolia/client-abtesting";
         ╵          ~~~~~~


✘ [ERROR] No matching export in "node_modules/@algolia/client-personalization/dist/builds/node.js" for import "EventType"

    node_modules/algoliasearch/dist/node.js:57:9:
      57 │ import { EventType } from "@algolia/client-personalization";
```

**Comment by Haroenv** [comment] 2024-10-21 12:05
This is a duplicate of https://github.com/algolia/algoliasearch-client-javascript/issues/1565, which has a merged but not yet released PR, will be fixed soon!

**Closed by Haroenv** 2024-10-21 12:05 UTC
Labels: bug
