### ISSUE TITLE
Cannot find name 'Exclude'

### ISSUE THREAD

**Issue by adryy5** [algolia/algoliasearch-client-javascript#753] opened 2019-04-29 07:28 UTC
There is a bug on runtime with version 3.32.1 in a Ionic 3 project.

Steps:

1. npm install algolia and types
2. ionic serve

**What is the current behavior?**

typescript: node_modules/@types/algoliasearch/index.d.ts, line: 14 
            Cannot find name 'Exclude'. 

      L14:   * Query on multiple index       
      L15:   * https://github.com/algolia/algoliasearch-client-js#multiple-queries---multiplequeries

I can't share code. I hope that somebody can help me. Thanks

**Comment by Haroenv** [comment] 2019-04-29 07:52
You have to use a TypeScript version over version 2.8 ([changelog](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html)). This is however unrelated to algoliasearch, so I will close this issue. Feel free to open an issue on DefinitelyTyped instead

**Closed by Haroenv** 2019-04-29 07:52 UTC

**Comment by adryy5** [comment] 2019-04-29 09:00
Sorry but I am using version 3.1.1 of Typescript. On Wednesday algolia was working perfectly, but on Thursday appear that problem and I am not able to fix that.

> You have to use a TypeScript version over version 2.8 ([changelog](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html)). This is however unrelated to algoliasearch, so I will close this issue. Feel free to open an issue on DefinitelyTyped instead

**Comment by Haroenv** [comment] 2019-04-29 09:18
In that case, a reproducible example will be necessary, since this is likely a problem with the configuration of TypeScript

**Comment by francoischalifour** [comment] 2019-04-29 12:37
I was able to reproduce the same issue using `algoliasearch/lite`.

```ts
import * as algoliasearch from 'algoliasearch/lite';
```

This throws:

> ERROR in node_modules/@types/algoliasearch/lite/index.d.ts(14,43): error TS2304: Cannot find name 'Exclude'.

The error comes from the [`Omit`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cc6de05e3347a9ad3651df02f4b87603758e4398/types/algoliasearch/lite/index.d.ts#L14) type in DefinitelyTyped.
