### ISSUE TITLE
Cannot import "lite" version of bundle with TypeScript

### ISSUE THREAD

**Issue by jhdevuk** [algolia/algoliasearch-client-javascript#666] opened 2018-02-19 17:04 UTC
Hi,

I'm currently implementing Algolia as our main search library, file size is very important to us so I'm attempting to use the "algoliasearchLite.js" file. How do I go about importing this using ES Module syntax?

We're using TypeScript which seems to provide types for the complete library but not for the lite version. Am I doing something wrong? I've tried:

import algolia from 'algoliasearch/lite';
import algolia from 'algoliasearch/algoliasearchLite';

Thanks for any help.

**Comment by Haroenv** [comment] 2018-02-25 16:58
You can also try to import from [`algoliasearch/src/browser/builds/algoliasearchLite.js`](https://github.com/algolia/algoliasearch-client-javascript/blob/develop/src/browser/builds/algoliasearchLite.js). I know TypeScript is sometimes quite peculiar about code bases not written in TypeScript itself. Can you leave a small project I can debug?

**Comment by vvo** [comment] 2018-02-28 14:40
@jhdevuk Can you create a repository demonstrating the issue? So that we can work on it ourselves. Thanks.

It seems you are having two different issues:
1. You can't import the lite version
2. Or you can but you don't have appropriates types for it

Can you confirm? Thanks

**Comment by Haroenv** [comment] 2018-03-21 08:44
closing because there wasn't given more information. Feel free to give more info and a way to reproduce this. A workaround should be to make a definition file for that "module" with definitions for client.search, client.addAlgoliaAgent, client.initIndex, index.searchForFacetValues. 

Will reopen with more information.

**Comment by jhdevuk** [comment] 2018-03-21 09:45
@Haroenv @vvo Sorry for the delay, have been meaning to do this for a while!

Here's a repository, it doesn't really do anything other than highlight the TypeScript error when importing the lite version of the Algolia package:

https://github.com/jhdevuk/typescript-algolia-lite

If you take a look at `./src/client/default.ts` you'll either notice an error in your IDE (VSCode) or when running the build:
```
npm install
gulp
```
![image](https://user-images.githubusercontent.com/13650046/37703108-81a85ae6-2cec-11e8-8990-350ad6e8fe45.png)
```
TS7016: Could not find a declaration file for module 'algoliasearch/lite'. 'C:\Users\jhill\Documents\Development\typescript-algolia-lite\node_modules\algoliasearch\lite.js' implicitly has an 'any' type.
```

Thanks again for any help.

**Comment by Haroenv** [comment] 2018-03-21 09:50
Thanks, we will take a look at that, sorry for closing the issue prematurely. I'll see if the issue is easy to solve in DefinitelyTyped

**Comment by jhdevuk** [comment] 2018-05-02 09:49
@haroenv Is there any update on this? Many thanks

**Comment by Haroenv** [comment] 2018-05-02 10:29
No update yet, sorry :)

**Comment by Haroenv** [comment] 2018-05-02 11:44
I've found a solution, will check if everything is correct and open a PR to DefinitelyTyped

**Comment by jhdevuk** [comment] 2018-05-02 11:56
@Haroenv Fantastic, look forward to hearing more. Thanks again

**Comment by jhdevuk** [comment] 2018-05-02 17:42
@Haroenv Will do once I'm back at a computer. Thanks

**Comment by Haroenv** [comment] 2018-05-18 08:01
This should be fixed now

**Closed by Haroenv** 2018-05-18 08:01 UTC
Labels: TypeScript, enhancement

**Comment by jhdevuk** [comment] 2018-05-18 08:09
@haroenv Yes thank you, all good!

**Comment by vvo** [comment] 2018-05-23 13:08
gg!

**Comment by fractalf** [comment] 2018-06-05 07:10
`import client from 'algoliasearch/lite'`
works fine

..but I would also expect this to work 
`import { lite as algoliasearch } from 'algoliasearch'`

**Comment by Haroenv** [comment] 2018-06-05 07:14
@fractalf I don't think that is possible, `algoliasearch/lite` is a different file / bundle to `algoliasearch`. Allowing to do both would easily enable the mistake to have both bundles in a single file. 

Note that in a future major we might reconsider this when our code is more in a place where it can be code split. Right now that isn't possible yet though

**Comment by marcobiedermann** [comment] 2020-05-16 10:58
I still get the same issue using TypeScript

```json
// package.json

"algoliasearch": "^4.2.0",
"react-instantsearch-dom": "^6.4.0",
"@types/react-instantsearch-dom": "^6.3.0",
```

```tsx
import algoliasearch from 'algoliasearch/lite';
import { InstantSearch, SearchBox } from 'react-instantsearch-dom';
```

Results in

```
Module '"node_modules/algoliasearch"' has no exported member 'Client'. Did you mean to use 'import Client from "node_modules/algoliasearch"' instead?

import { Client } from 'algoliasearch';

Namespace '"node_modules/algoliasearch/index"' has no exported member 'QueryParameters'.

export interface QueryParameters extends algoliasearch.QueryParameters {
```

As far as I can tell `algoliasearch` does provide Type Definitions but `react-instantsearch-dom` requires Types from DefinitelyTyped. I guess those two versions are incompatible

**Comment by Haroenv** [comment] 2020-05-18 07:51
@marcobiedermann this is likely because of a mismatch between underlying @types/algoliasearch-helper library (which you should remove) and the client v4; see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44699#issuecomment-629584573

**Comment by marcobiedermann** [comment] 2020-05-18 08:39
@Haroenv Thank you very much for your answer. Looking forward to getting this one in rather soon in order to continue with development. Thanks!

**Comment by Haroenv** [comment] 2020-05-18 09:59
@marcobiedermann you don't need to wait for that PR, you can specifically remove `@types/algoliasearch-helper` from your yarn.lock and it should not install it again
