### ISSUE TITLE
Angular 6 Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by diegotham** [algolia/algoliasearch-client-javascript#691] opened 2018-05-05 15:43 UTC
**UPDATE FROM MAINTAINERS**

The working workaround for this issue for now is to add:

```js
(window as any).process = {
  env: { DEBUG: undefined },
};
```

**/UPDATE FROM MAINTAINERS**

to your polyfill.ts file in you Angular app

**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Angular does not provide a shim for "process" anymore (https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814). 

Error:

```
Uncaught ReferenceError: process is not defined
    at Object../node_modules/algoliasearch/src/AlgoliaSearchCore.js (vendor.js:175349)
    at __webpack_require__ (runtime.js:82)
    at Object../node_modules/algoliasearch/src/AlgoliaSearch.js (vendor.js:174675)
    at __webpack_require__ (runtime.js:82)
    at Object../node_modules/algoliasearch/src/browser/builds/algoliasearch.js (vendor.js:177945)
    at __webpack_require__ (runtime.js:82)
...
```

**If the current behavior is a bug, please provide all the steps to reproduce and a minimal
[JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install`
and `npm start`.**
Just using the library in an Angular 6 throws the error

**What is the expected behavior?**
To use algoliasearch library in an Angular 6 app

**Comment by Haroenv** [comment] 2018-05-05 16:43
Hey @diegotham, I think I have a fix for this (https://github.com/algolia/algoliasearch-client-javascript/pull/692), but to test it out correctly, I’d need to check in a real app, would it be possible for you to give a minimal reproduction in a GitHub repo please? Thanks!

**Comment by 0x6368656174** [comment] 2018-05-09 09:10
Workaround: `const algoliasearch = require ('algoliasearch/dist/algoliasearch.js');`. Most likely, the problem with the fact that in `package.json` in `browser` not those paths are specified.

**Comment by Haroenv** [comment] 2018-05-09 09:17
Yes, @0x6368656174, both that would work, as well as `const algoliasearch = require ('algoliasearch/dist/algoliasearchLite.min.js');` for a smaller version.

Note that you can also shim process as described in https://github.com/algolia/angular-instantsearch/issues/90#issuecomment-387028504 in `polyfill.ts`:

```ts
(window as any).process = {
  env: { DEBUG: undefined },
};
```

**Comment by ArsalRaza** [comment] 2018-05-24 03:19
I'm also getting the same issue

**Comment by trsh** [comment] 2018-05-24 12:49
Same here

**Comment by Haroenv** [comment] 2018-05-24 13:05
Did you read the workaround @ArsalRaza @trsh ?

**Comment by vvo** [comment] 2018-05-25 08:40
The working workaround for this issue for now is to add:

```js
(window as any).process = {
  env: { DEBUG: undefined },
};
```

to your polyfill.ts file in you Angular app, locking this issue since the workaround is easy for now. Until we find the right solution.

**Closed** 2018-06-12 09:20 UTC
